Docker 3
Otus-DevOps-2017-11/KirilBuzan_microservices pull request #3
Opened 2018-03-10 14:30 UTC by KirillBuzan

Выполнено домашнее задание №16. Шаги выполнения описаны в файле README.MD. Выполнены все задания со *

2018-03-12 18:46 UTC, serjs commented on reddit-microservices/ui/Dockerfile
> +RUN apk update &&\
Как по мне, лучше привести к такому виду по синтаксису
```
RUN apk update && \
        apk add --no-cache build-base ruby ruby-bundler ruby-dev ruby-json && \
        gem install bundler --no-ri --no-rdoc && \
        rm -rf /var/cache/apk/*
```

2018-03-12 18:47 UTC, serjs commented on reddit-microservices/ui/Dockerfile
> +COPY Gemfile* "$APP_HOME/"
Переменные для сборки $APP_HOME переменную можно без кавычек в этих случаях использовать

2018-03-12 18:48 UTC, serjs commented on reddit-microservices/ui/Dockerfile
> +ENV POST_SERVICE_HOST=post \
BTW, такая интерпретация ENV переменных не будет работать. У тебя получится одна POST_SERVICE_HOST переменная со значением `post POST_SERVICE_PORT=5000 COMMENT_SERVICE_HOST=comment COMMENT_SERVICE_PORT=9292`

Можешь сам проверить через docker inspect после запуска контейнера.

ПО идее еще приложение не должно работать с такой интерпретацией, т.к. часть переменных не будет передана

2018-03-12 18:53 UTC, serjs requested changes
Привет!

Вижу ряд оптимизаций, это хорошо, но нужно сделать пару изменений

Я отписал по ENV инструкции, к сожалению ее в один слой не описать таким способом как ты сделал. Энв переменные работают по key=value конструкциям.

Ну и чуть сахара в комментах, остальное ок. Поправь и обнови PR для всех Dockerfile по ENV инструкции - я заапрувлю

2018-03-12 19:20 UTC, KirillBuzan commented on reddit-microservices/ui/Dockerfile
> +RUN apk update &&\
Привел к предложенному виду, это я чтобы не запутаться делал) добавлял по чуть-чуть. не сразу к такому набору пришел

2018-03-12 19:22 UTC, KirillBuzan commented on reddit-microservices/ui/Dockerfile
> +COPY Gemfile* "$APP_HOME/"
В кавычки добавил от отчаяния) Была проблема со сборкой данной образа. Но проблема потом оказалась не в кавычках. Исправил

2018-03-12 19:24 UTC, KirillBuzan commented on reddit-microservices/ui/Dockerfile
> +ENV POST_SERVICE_HOST=post \
ПО работало без проблем) иначе бы не стал выкладывать.Учусь же ради знаний, а не ради того чтобы сдать) 
Сергей, спасибо большое за твои комментарии. Учту на будущее.

2018-03-12 19:25 UTC, KirillBuzan commented on reddit-microservices/ui/Dockerfile
> +ENV POST_SERVICE_HOST=post \
Исправил во всех Dockerfile определение ENV

2018-03-14 17:28 UTC, KirillBuzan commented
Сергей, добрый день. Произвел все исправлеия

2018-03-15 07:55 UTC, serjs commented on reddit-microservices/README.md
> +# Microservices
Readme.md можно оставить только в корне репо, он у тебя и так уже есть.

2018-03-15 07:57 UTC, serjs approved these changes
Приветствую!

Спасибо за выполненное ДЗ. Блокирующих к мержу замечаний нет 👍

2018-03-16 16:54 UTC, merged